apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-main
  template:
    metadata:
      labels:
        app: dummy-main
    spec:
      containers:
      - name: dummy
        image: alpine:3.18
        command: ["sh", "-c", "sleep 3600"]
